### PR TITLE
Created README

### PR DESCRIPTION
**Pull request by leader80**
Added a first ReadMe file as reference for the multiple projects across ili2db.

Please include it in the repository, so that we can improve the UX.

Thanks
G

### CODE REVIEW

**Comment by claeis** [comment]
- Please use .rst instead of .md
- Please do not repeat doc/ili2db.rst just link to it

**Comment by pka** [comment]
@leader80 See [here](http://rst.ninjs.org/?n=ee95dbd2965618ebccfd37a4948bc837&theme=basic) for a Pandoc converted version of your README.md

**Comment by leader80** [comment]
@claeis the standard readme for github is usually md format: https://guides.github.com/features/wikis/#creating-a-readme
@pka thanks

**Comment by claeis** [comment]
I used .rst for the main doc, because it is used by the python community. So I expect the tooling to be mature. I want to keep all documentation in the same markup format.

**Comment by leader80** [comment]
Okay let me convert the rst to the standard format I'll push a PR once done, I'll also clean the main Readme to make it point to the separate documentation. But the standard should be respected.

**Pull request closed without merging**
